# Generated by Django 3.1.2 on 2020-11-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201105_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Processing'), ('2', 'Pending'), ('3', 'On Hold'), ('4', 'Open'), ('5', 'Complete'), ('6', 'Closed'), ('7', 'Canceled')], default='1', max_length=20),
        ),
    ]
