# Generated by Django 3.1.2 on 2020-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201105_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'P'), ('Pending', 'PN'), ('On Hold', 'OH'), ('Open', 'O'), ('Complete', 'C'), ('Closed', 'CLS'), ('Canceled', 'CL')], default='Processing', max_length=20),
        ),
    ]
