# Generated by Django 3.1.2 on 2020-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201105_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'primary'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Open', 'Open'), ('Complete', 'Complete'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], max_length=20),
        ),
    ]
